version: "3.8"

services:
  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - fpm
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8000:8000"
    volumes:
      - ./etc/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/minisymfony/web

  fpm:
    image: 1maa/php-dev:8.1
    volumes:
      - .:/var/www/minisymfony
    working_dir: /var/www/minisymfony
